'use strict';var mathx=require("@lost-types/mathx");function _classCallCheck(b,h){if(!(b instanceof h))throw new TypeError("Cannot call a class as a function");}function _defineProperties(b,h){for(var f=0;f<h.length;f++){var g=h[f];g.enumerable=g.enumerable||!1;g.configurable=!0;"value"in g&&(g.writable=!0);Object.defineProperty(b,g.key,g)}}function _createClass(b,h,f){h&&_defineProperties(b.prototype,h);f&&_defineProperties(b,f);return b}
function _toConsumableArray(b){return _arrayWithoutHoles(b)||_iterableToArray(b)||_nonIterableSpread()}function _arrayWithoutHoles(b){if(Array.isArray(b)){for(var h=0,f=Array(b.length);h<b.length;h++)f[h]=b[h];return f}}function _iterableToArray(b){if(Symbol.iterator in Object(b)||"[object Arguments]"===Object.prototype.toString.call(b))return Array.from(b)}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}
var runtime=function(b){function h(a,c,d,f){c=Object.create((c&&c.prototype instanceof g?c:g).prototype);f=new A(f||[]);c._invoke=I(a,d,f);return c}function f(a,c,d){try{return{type:"normal",arg:a.call(c,d)}}catch(v){return{type:"throw",arg:v}}}function g(){}function m(){}function k(){}function q(a){["next","throw","return"].forEach(function(c){a[c]=function(a){return this._invoke(c,a)}})}function l(a,c){function d(e,b,g,v){e=f(a[e],a,b);if("throw"===e.type)v(e.arg);else{var h=e.arg;return(e=h.value)&&
"object"===typeof e&&r.call(e,"__await")?c.resolve(e.__await).then(function(a){d("next",a,g,v)},function(a){d("throw",a,g,v)}):c.resolve(e).then(function(a){h.value=a;g(h)},function(a){return d("throw",a,g,v)})}}var b;this._invoke=function(a,f){function e(){return new c(function(c,e){d(a,f,c,e)})}return b=b?b.then(e,e):e()}}function I(a,c,d){var b=D;return function(e,g){if(b===E)throw Error("Generator is already running");if(b===x){if("throw"===e)throw g;return F()}d.method=e;for(d.arg=g;;){if(e=
d.delegate)if(e=G(e,d)){if(e===n)continue;return e}if("next"===d.method)d.sent=d._sent=d.arg;else if("throw"===d.method){if(b===D)throw b=x,d.arg;d.dispatchException(d.arg)}else"return"===d.method&&d.abrupt("return",d.arg);b=E;e=f(a,c,d);if("normal"===e.type){b=d.done?x:J;if(e.arg===n)continue;return{value:e.arg,done:d.done}}"throw"===e.type&&(b=x,d.method="throw",d.arg=e.arg)}}}function G(a,c){var d=a.iterator[c.method];if(d===p){c.delegate=null;if("throw"===c.method){if(a.iterator["return"]&&(c.method=
"return",c.arg=p,G(a,c),"throw"===c.method))return n;c.method="throw";c.arg=new TypeError("The iterator does not provide a 'throw' method")}return n}d=f(d,a.iterator,c.arg);if("throw"===d.type)return c.method="throw",c.arg=d.arg,c.delegate=null,n;d=d.arg;if(!d)return c.method="throw",c.arg=new TypeError("iterator result is not an object"),c.delegate=null,n;if(d.done)c[a.resultName]=d.value,c.next=a.nextLoc,"return"!==c.method&&(c.method="next",c.arg=p);else return d;c.delegate=null;return n}function K(a){var c=
{tryLoc:a[0]};1 in a&&(c.catchLoc=a[1]);2 in a&&(c.finallyLoc=a[2],c.afterLoc=a[3]);this.tryEntries.push(c)}function B(a){var c=a.completion||{};c.type="normal";delete c.arg;a.completion=c}function A(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(K,this);this.reset(!0)}function C(a){if(a){var c=a[y];if(c)return c.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var d=-1;c=function e(){for(;++d<a.length;)if(r.call(a,d))return e.value=a[d],e.done=!1,e;e.value=p;e.done=!0;return e};
return c.next=c}}return{next:F}}function F(){return{value:p,done:!0}}var H=Object.prototype,r=H.hasOwnProperty,p,t="function"===typeof Symbol?Symbol:{},y=t.iterator||"@@iterator",L=t.asyncIterator||"@@asyncIterator",z=t.toStringTag||"@@toStringTag";b.wrap=h;var D="suspendedStart",J="suspendedYield",E="executing",x="completed",n={};t={};t[y]=function(){return this};var u=Object.getPrototypeOf;(u=u&&u(u(C([]))))&&u!==H&&r.call(u,y)&&(t=u);var w=k.prototype=g.prototype=Object.create(t);m.prototype=w.constructor=
k;k.constructor=m;k[z]=m.displayName="GeneratorFunction";b.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===m||"GeneratorFunction"===(a.displayName||a.name):!1};b.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,k):(a.__proto__=k,z in a||(a[z]="GeneratorFunction"));a.prototype=Object.create(w);return a};b.awrap=function(a){return{__await:a}};q(l.prototype);l.prototype[L]=function(){return this};b.AsyncIterator=l;b.async=function(a,c,d,f,e){void 0===
e&&(e=Promise);var g=new l(h(a,c,d,f),e);return b.isGeneratorFunction(c)?g:g.next().then(function(a){return a.done?a.value:g.next()})};q(w);w[z]="Generator";w[y]=function(){return this};w.toString=function(){return"[object Generator]"};b.keys=function(a){var c=[],d;for(d in a)c.push(d);c.reverse();return function e(){for(;c.length;){var d=c.pop();if(d in a)return e.value=d,e.done=!1,e}e.done=!0;return e}};b.values=C;A.prototype={constructor:A,reset:function(a){this.next=this.prev=0;this.sent=this._sent=
p;this.done=!1;this.delegate=null;this.method="next";this.arg=p;this.tryEntries.forEach(B);if(!a)for(var c in this)"t"===c.charAt(0)&&r.call(this,c)&&!isNaN(+c.slice(1))&&(this[c]=p)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function c(c,e){f.type="throw";f.arg=a;d.next=c;e&&(d.method="next",d.arg=p);return!!e}if(this.done)throw a;for(var d=this,b=this.tryEntries.length-1;0<=b;--b){var e=this.tryEntries[b],
f=e.completion;if("root"===e.tryLoc)return c("end");if(e.tryLoc<=this.prev){var g=r.call(e,"catchLoc"),h=r.call(e,"finallyLoc");if(g&&h){if(this.prev<e.catchLoc)return c(e.catchLoc,!0);if(this.prev<e.finallyLoc)return c(e.finallyLoc)}else if(g){if(this.prev<e.catchLoc)return c(e.catchLoc,!0)}else if(h){if(this.prev<e.finallyLoc)return c(e.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,c){for(var d=this.tryEntries.length-1;0<=d;--d){var b=this.tryEntries[d];
if(b.tryLoc<=this.prev&&r.call(b,"finallyLoc")&&this.prev<b.finallyLoc){var e=b;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=c&&c<=e.finallyLoc&&(e=null);d=e?e.completion:{};d.type=a;d.arg=c;return e?(this.method="next",this.next=e.finallyLoc,n):this.complete(d)},complete:function(a,c){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&c&&(this.next=c);return n},
finish:function(a){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.finallyLoc===a)return this.complete(d.completion,d.afterLoc),B(d),n}},"catch":function(a){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc===a){a=d.completion;if("throw"===a.type){var b=a.arg;B(d)}return b}}throw Error("illegal catch attempt");},delegateYield:function(a,c,d){this.delegate={iterator:C(a),resultName:c,nextLoc:d};"next"===this.method&&(this.arg=p);return n}};
return b}("object"===typeof module?module.exports:{});try{regeneratorRuntime=runtime}catch(b){Function("r","regeneratorRuntime = r")(runtime)}function checkLength(){if(4294967295<this.length)throw Error("Cannot iterate infinite size range");}function normalizeStep(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:1;b=+b;Number.isNaN(b)&&(b=1);if(0===b||0>b)throw TypeError("Step cannot be 0 or negative number");return b}
var Range=function(){function b(){var h=0<arguments.length&&void 0!==arguments[0]?arguments[0]:0,f=1<arguments.length?arguments[1]:void 0,g=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1;_classCallCheck(this,b);var m=1<arguments.length?+h:0;h=1<arguments.length?+f:+h;Number.isNaN(m)||Number.isNaN(h)||!arguments.length||(g=normalizeStep(g),Object.defineProperties(this,{from:{value:m},to:{value:h},step:{value:g}}))}_createClass(b,[{key:Symbol.iterator,value:regeneratorRuntime.mark(function f(){var b,
m,k;return regeneratorRuntime.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:checkLength.call(this),b=this.from<=this.to,m=Math.max(mathx.getPrecision(this.step),mathx.getPrecision(this.from),mathx.getPrecision(this.to)),k=this.from;case 4:if(!(b?k<=this.to:k>=this.to)){f.next=10;break}f.next=7;return k;case 7:k=+(b?k+this.step:k-this.step).toFixed(m);f.next=4;break;case 10:case "end":return f.stop()}},f,this)})},{key:"forEach",value:function(b){var f=1<arguments.length&&void 0!==arguments[1]?
arguments[1]:this.step;checkLength.call(this);f=normalizeStep(f);for(var m=this.from<=this.to,k=Math.max(mathx.getPrecision(f),mathx.getPrecision(this.from),mathx.getPrecision(this.to)),q=0,l=this.from;m?l<=this.to:l>=this.to;l=+(m?l+f:l-f).toFixed(k))b(l,q,this),q+=1}},{key:"forEachReverse",value:function(b){var f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:this.step;checkLength.call(this);f=normalizeStep(f);for(var m=this.from<=this.to,k=Math.max(mathx.getPrecision(f),mathx.getPrecision(this.from),
mathx.getPrecision(this.to)),q=0,l=this.to;m?l>=this.from:l<=this.from;l=+(m?l-f:l+f).toFixed(k))b(l,q,this),q+=1}},{key:"has",value:function(b){return+b>=this.min&&+b<=this.max}},{key:"clamp",value:function(b){return+b<this.min?this.min:+b>this.max?this.max:+b}},{key:"toArray",value:function(){return _toConsumableArray(this)}},{key:"getFraction",value:function(b){var f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:12;if(Number.isNaN(+f)||0>+f)return NaN;100<f&&(f=100);return+((+b-this.min)/
(this.max-this.min)).toFixed(f)}},{key:"fromFraction",value:function(b){return+(this.min+ +b*(this.max-this.min)).toFixed(1<arguments.length&&void 0!==arguments[1]?arguments[1]:12)}},{key:"slice",value:function(b){if(!b)return[];b=+((this.max-this.min+this.step)/b).toFixed(12);var f=[];this.forEach(function(b){return f.push(b)},b);return f}},{key:"mod",value:function(b){return this.min+mathx.modulo(+b,this.max-this.min+1)}},{key:"length",get:function(){return void 0===this.to||void 0===this.from?
0:Math.round(Math.abs(this.to-this.from)/this.step)+1}},{key:"max",get:function(){return this.from<=this.to?this.to:this.from}},{key:"min",get:function(){return this.from<=this.to?this.from:this.to}},{key:"center",get:function(){if(void 0!==this.to&&void 0!==this.from)return this.min+(this.max-this.min)/2}}],[{key:"from",value:function(f){if(null==f||"function"!==typeof f[Symbol.iterator]||void 0!==f.length&&!f.length||void 0!==f.size&&!f.size)return new b;var g=Math.min.apply(Math,_toConsumableArray(f));
f=Math.max.apply(Math,_toConsumableArray(f));return new b(g,f)}}]);return b}();module.exports=Range
